# **Cheminformatics Project - Computational Drug Discovery [Part 3] Descriptor Calculation and Dataset Preparation**

Zeinab Alaa

In this Jupyter notebook, we will be building a real-life **data science project** that you can include in your **data science portfolio**. Particularly, we will be building a machine learning model using the ChEMBL bioactivity data.

In **Part 3**, we will be calculating molecular descriptors that are essentially quantitative description of the compounds in the dataset. Finally, we will be preparing this into a dataset for subsequent model building in Part 4.

---

## **Download PaDEL-Descriptor**

In [1]:
%%capture
! wget https://github.com/dataprofessor/bioinformatics/raw/master/padel.zip
! wget https://github.com/dataprofessor/bioinformatics/raw/master/padel.sh

In [2]:
! unzip padel.zip

unzip:  cannot find or open padel.zip, padel.zip.zip or padel.zip.ZIP.

## **Load bioactivity data**

Download the curated ChEMBL bioactivity data that has been pre-processed from Parts 1 and 2 of this Bioinformatics Project series. Here we will be using the **bioactivity_data_3class_pIC50.csv** file that essentially contain the pIC50 values that we will be using for building a regression model.

In [3]:
import pandas as pd

In [4]:
df3 = pd.read_csv('EpidermalGrowthFactor_04_bioactivity_data_3class_pIC50.csv')

In [5]:
df3

,Unnamed: 0,molecule_chembl_id,canonical_smiles,class,MW,LogP,NumHDonors,NumHAcceptors,pIC50
0,0,CHEMBL292323,COc1cccc2c(C(=O)Nc3ccccc3)c(SSc3c(C(=O)Nc4cccc...,inactive,622.772,7.9912,2.0,8.0,4.000000
1,1,CHEMBL304414,Cn1c(SSc2c(C(=O)Nc3ccccc3)c3ccccc3n2C)c(C(=O)N...,inactive,562.720,7.9740,2.0,6.0,4.000000
2,2,CHEMBL62176,CN1C(=S)C(C(=O)Nc2ccccc2)c2ccccc21,inactive,282.368,3.1861,1.0,2.0,4.000000
3,3,CHEMBL62701,Cn1c(SSc2c(C(=O)Nc3ccccc3)c3cccnc3n2C)c(C(=O)N...,inactive,564.696,6.7640,2.0,8.0,4.602060
4,4,CHEMBL137617,C/N=N/Nc1ccc2ncnc(Nc3cccc(Br)c3)c2c1,active,357.215,4.5448,2.0,5.0,7.154902
...,...,...,...,...,...,...,...,...,...
86,86,CHEMBL5593705,CS(=O)(=O)c1ccc(NC(=O)c2cc(-c3ccc(Cl)cc3)n(-c3...,intermediate,451.935,4.8485,1.0,5.0,5.769551
87,87,CHEMBL1336,CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)...,intermediate,464.831,5.5497,3.0,4.0,5.455932
88,88,CHEMBL939,COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1OCCCN1CCOCC1,active,446.910,4.2756,1.0,7.0,7.841638
89,89,CHEMBL553,C#Cc1cccc(Nc2ncnc3cc(OCCOC)c(OCCOC)cc23)c1,active,393.443,3.4051,1.0,7.0,7.714443
90,90,CHEMBL545315,C=CC(=O)Nc1cc2c(Nc3ccc(F)c(Cl)c3)ncnc2cc1OCCCN...,active,485.947,4.3915,2.0,7.0,8.795880

In [6]:
selection = ['canonical_smiles','molecule_chembl_id']
df3_selection = df3[selection]
df3_selection.to_csv('molecule.smi', sep='\t', index=False, header=False)

In [7]:
! cat molecule.smi | head -5

COc1cccc2c(C(=O)Nc3ccccc3)c(SSc3c(C(=O)Nc4ccccc4)c4cccc(OC)c4n3C)n(C)c12	CHEMBL292323
Cn1c(SSc2c(C(=O)Nc3ccccc3)c3ccccc3n2C)c(C(=O)Nc2ccccc2)c2ccccc21	CHEMBL304414
CN1C(=S)C(C(=O)Nc2ccccc2)c2ccccc21	CHEMBL62176
Cn1c(SSc2c(C(=O)Nc3ccccc3)c3cccnc3n2C)c(C(=O)Nc2ccccc2)c2cccnc21	CHEMBL62701
C/N=N/Nc1ccc2ncnc(Nc3cccc(Br)c3)c2c1	CHEMBL137617

In [8]:
! cat molecule.smi | wc -l

91

## **Calculate fingerprint descriptors**

### **Calculate PaDEL descriptors**

In [13]:
! cat padel.sh

cat: padel.sh: No such file or directory

In [14]:
! bash padel.sh

bash: padel.sh: No such file or directory

In [11]:
! ls -l

total 24
-rw-r--r-- 1 root root 11914 Feb 21 19:53 EpidermalGrowthFactor_04_bioactivity_data_3class_pIC50.csv
-rw-r--r-- 1 root root  5478 Feb 21 19:54 molecule.smi
drwxr-xr-x 1 root root  4096 Jan 16 14:24 sample_data

## **Preparing the X and Y Data Matrices**

### **X data matrix**

In [15]:
df3_X = pd.read_csv('descriptors_output.csv')

In [ ]:
df3_X

               Name  PubchemFP0  ...  PubchemFP879  PubchemFP880
0      CHEMBL336398           1  ...             0             0
1      CHEMBL133897           1  ...             0             0
2      CHEMBL130628           1  ...             0             0
3      CHEMBL131588           1  ...             0             0
4      CHEMBL130478           1  ...             0             0
...             ...         ...  ...           ...           ...
4690  CHEMBL4293155           1  ...             0             0
4691  CHEMBL4282558           1  ...             0             0
4692  CHEMBL4281727           1  ...             0             0
4693  CHEMBL4292349           1  ...             0             0
4694  CHEMBL4278260           1  ...             0             0

[4695 rows x 882 columns]

In [16]:
df3_X = df3_X.drop(columns=['Name'])
df3_X

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,1,1,1,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,1,1,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,1,1,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,1,0,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,1,0,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1759,1,1,1,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1760,1,1,1,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1761,1,1,1,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1762,1,1,1,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1763,1,1,1,0,0,0,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## **Y variable**

### **Convert IC50 to pIC50**

In [17]:
df3_Y = df3['pIC50']
df3_Y

0     4.000000
1     4.000000
2     4.000000
3     4.602060
4     7.154902
        ...
86    5.769551
87    5.455932
88    7.841638
89    7.714443
90    8.795880
Name: pIC50, Length: 91, dtype: float64

## **Combining X and Y variable**

In [18]:
dataset3 = pd.concat([df3_X,df3_Y], axis=1)
dataset3

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880,pIC50
0,1,1,1,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.000000
1,1,1,1,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.000000
2,1,1,1,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.000000
3,1,1,0,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.602060
4,1,1,0,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.154902
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1759,1,1,1,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1760,1,1,1,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1761,1,1,1,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1762,1,1,1,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1763,1,1,1,0,0,0,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
dataset3.to_csv('EpidermalGrowthFactor_06_bioactivity_data_3class_pIC50_pubchem_fp.csv', index=False)

# **Let's download the CSV file to your local computer for the Part 3B (Model Building).**